### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by bobonov** [theramenrobotdiscocode/lemur-engine#10]
**Is your feature request related to a problem? Please describe.**
When saving categories you are redirected to the list, while in most cases would be better to stay in editing.
When implementing a bot very often you save a "step" test it and then make correction

**Describe the solution you'd like**
Two different buttons, 
"save" that redirect you to the list
"update and continue" that keep you on the category form

**Comment by elizaibeth** [comment]
Great feature! Will get that sorted thanks

**Comment by elizaibeth** [comment]
This feature has been created now and is part of the latest release 
Please see the release notes for more info
Thanks for the request!
https://github.com/theramenrobotdiscocode/lemur-engine/releases/tag/v1.2.0
