### ISSUE TITLE
[BotBug] table field turns.input should be text

### ISSUE THREAD

**Issue by bobonov** [theramenrobotdiscocode/lemur-engine#9]
Describe the bug
When a user writes a message longer than 256 we get an insert error.
It is very unlike to receive in input a so long message, but it can happen that a user just to try (or for real need) write so much.
changing turns.input from varchar to text "solve" (postpone to a longer text) the error and make it in line with turns.output field, which is text
Maybe is also worth to truncate the string before saving it to db even if this means to partially loose the message 

To Reproduce
Just write a long message

User Says: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
Bot Responds With Error: 
QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'input' at row 1 (SQL: insert into `turns` (`conversation_id`, `parent_turn_id`, `input`, `status`, `source`, `slug`, `updated_at`, `created_at`) .....

Expected behavior
No error and the message being saved and bot continue to process

AIML Categories
General error

**Comment by elizaibeth** [comment]
Thank you I will look into this now

**Comment by elizaibeth** [comment]
This feature has been created now and is part of the latest release 
Please see the release notes for more info
Thanks for the request!
https://github.com/theramenrobotdiscocode/lemur-engine/releases/tag/v1.2.0
